config/routes.rb
# encoding: UTF-8

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/advanced-roadmap
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

get "milestones/total_graph", :to => "milestones#total_graph"
resources :projects do
  resources :milestones, :only => [:new, :create, :index]
end
resources :milestones, :only => [:show, :edit, :update, :destroy]

app/models/milestone.rb
# encoding: UTF-8

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/advanced-roadmap
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

class Milestone < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :project
  has_many :milestone_versions, :dependent => :destroy
  has_many :versions, :through => :milestone_versions

  include Redmine::SafeAttributes
  safe_attributes :name, :description, :milestone_effective_date
  attr_protected :id

  validates_presence_of :name
  validates_uniqueness_of :name, :scope => [:project_id]
  validates_length_of :name, :maximum => 60
  validates_format_of :milestone_effective_date, :with => /\A\d{4}-\d{2}-\d{2}\z/,
                      :message => 'activerecord_error_not_a_date', :allow_nil => true
  
  def to_s
    name
  end
  
  def <=>(milestone)
    if self.milestone_effective_date
      if milestone.milestone_effective_date
        if self.milestone_effective_date == milestone.milestone_effective_date
          self.name <=> milestone.name
        else
          self.milestone_effective_date <=> milestone.milestone_effective_date
        end
      else
        -1
      end
    else
      if milestone.milestone_effective_date
        1
      else
        self.name <=> milestone.name
      end
    end
  end

  def versions?(version)
    versions.index(version) != nil
  end

  def completed?
    milestone_effective_date && (milestone_effective_date <= Date.today)
  end

  def is_a?(o)
    return true if o == Version
    super
  end

  def self.estimated_due_date(totals)
    estimated_due_date = nil
    non_working_week_days = Setting.non_working_week_days.map{ |day| day.to_i % 7 }
    if (non_working_week_days.count < 7)
      days = (totals[:parallel_rest_hours] / 8.0).ceil
      estimated_due_date = DateTime.now
      while days > 1
        days -= 1 unless non_working_week_days.include?(estimated_due_date.wday)
        estimated_due_date += 1.days
      end
    end
    return estimated_due_date
  end

end

app/models/milestone_version.rb
# encoding: UTF-8

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/advanced-roadmap
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

class MilestoneVersion < ActiveRecord::Base
  
  belongs_to :milestone
  belongs_to :version

end

app/controllers/milestones_controller.rb
# encoding: UTF-8

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/advanced-roadmap
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

require 'advanced_roadmap/gruff/pie' if Object.const_defined?(:Magick)

class MilestonesController < ApplicationController
  
  menu_item :roadmap
  model_object Milestone

  before_filter :find_model_object,
                :only => [:show, :edit, :update, :destroy]
  before_filter :find_project_from_association,
                :only => [:show, :edit, :update, :destroy]
  before_filter :find_project_by_project_id,
                :only => [:new, :create]
  before_filter :authorize, :except => [:show, :total_graph]

  helper :custom_fields
  helper :projects
  helper :versions
  include CustomFieldsHelper
  include ProjectsHelper
  include VersionsHelper

  def show
    projects = {}
    @milestone.versions.each do |version|
      version.fixed_issues.each do |issue|
        if !(projects.include?(issue.project.id))
          projects[issue.project.id] = issue.project.id
        end
      end
    end
    Version.sort_versions(@milestone.versions)
    @more_than_one_project = (projects.length > 1)
    @totals = Version.calculate_totals(@milestone.versions)
  end

  def new
    @projects = Project.active.sort { |a, b| a.name.downcase <=> b.name.downcase }
    @versions = @project.versions
    @milestone = Milestone.new
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def create
    @milestone = @project.milestones.build(params[:milestone])
    @milestone.user_id = User.current.id
    if request.post? and @milestone.save
      if params[:versions]
        params[:versions].each do |version|
          milestone_version = MilestoneVersion.new
          milestone_version.milestone_id = @milestone.id
          milestone_version.version_id = version
          milestone_version.save
        end
       end
      flash[:notice] = l(:notice_successful_create)
      redirect_to :controller => :projects, :action => :settings, :tab => 'milestones', :id => @project
    end
  rescue ActiveRecord::RecordNotFound => e
    render_404
  end

  def edit
    @projects = Project.active.sort { |a, b| a.name.downcase <=> b.name.downcase }
    @versions = @project.versions
  end

  def update
    @projects = Project.all.sort { |a, b| a.name.downcase <=> b.name.downcase }
    @versions = @project.versions
    versions_to_delete = @milestone.versions
    versions_to_add = []
    if params[:versions]
      params[:versions].each do |version|
        index = @milestone.versions.index(version)
        if index != nil
          versions_to_delete.remove(index)
        else
          versions_to_add << version
        end
      end
    end
    if @milestone.update_attributes(params[:milestone])
      versions_to_delete.each do |version|
        milestone_version = MilestoneVersion.where(:milestone_id => @milestone.id, :version_id => version.id).first
        milestone_version.destroy
      end
      versions_to_add.each do |version|
        milestone_version = MilestoneVersion.new
        milestone_version.milestone_id = @milestone.id
        milestone_version.version_id = version
        milestone_version.save
      end
      flash[:notice] = l(:notice_successful_update)
      redirect_to :controller => :projects, :action => :settings, :tab => 'milestones', :id => @project
    end
  end

  def destroy
    @milestone.destroy
    redirect_to :controller => :projects, :action => :settings, :tab => 'milestones', :id => @project
  rescue
    flash[:error] = l(:notice_unable_delete_milestone, :milestone_label => milestone_label)
    redirect_to :controller => :projects, :action => :settings, :tab => 'milestones', :id => @project
  end

  def total_graph
    if Object.const_defined?(:Magick)
      g = AdvancedRoadmap::Gruff::Pie.new(params[:size] || '500x400')
      g.hide_title = true
      g.theme = graph_theme
      g.margins = 0

      versions = params[:versions] || []
      percentajes = params[:percentajes] || []
      i = 0
      while i < versions.size and i < percentajes.size
        percentajes[i] = percentajes[i].to_f
        g.data(versions[i], percentajes[i])
        i += 1
      end

      headers['Content-Type'] = 'image/png'
      send_data(g.to_blob, :type => 'image/png', :disposition => 'inline')
    end
  end

private

  def graph_theme
    {
      :colors => ['#DB2626', '#6A6ADB', '#64D564', '#F727F7', '#EBEB20', '#303030', '#12ABAD',
                  '#808080', '#B7580B', '#316211'],
      :marker_color => '#AAAAAA',
      :background_colors => ['#FFFFFF', '#FFFFFF']
    }
  end

end

app/views/projects/settings/_milestones.html.erb
<% if @project.milestones.any? %>
<table class="list">
  <thead>
    <th style="text-align: left;"><%= label_milestone %></th>
    <th style="text-align: center;"><%= l(:field_effective_date) %></th>
    <th style="text-align: left;"><%= l(:field_description) %></th>
    <th style="text-align: center;"><%= l(:label_version_plural) %></th>
    <th style="width:15%"></th>
    <th style="width:15%"></th>
  </thead>
  <tbody>
  <% for milestone in @project.milestones.sort %>
    <tr class="<%= cycle 'odd', 'even' %>">
      <td style="text-align: left;">
        <%= link_to h(milestone.name), :controller => :milestones, :action => :show, :id => milestone.id %>
      </td>
      <td style="text-align: center;"><%= format_date(milestone.milestone_effective_date) %></td>
      <td style="text-align: left;"><%=h milestone.description %></td>
      <td style="text-align: center;">
        <%= milestone.versions.sort { |a, b|
              a.name.downcase <=> b.name.downcase
            }.collect { |v|
              link_to(h(v.name), :controller => :versions, :action => :show, :id => v)
            }.join(', ').html_safe %>
      </td>
      <td style="text-align: center;">
        <%- if User.current.allowed_to?(:manage_milestones, @project) -%>
          <%= link_to(l(:button_edit), edit_milestone_path(milestone),
                      :class => 'icon icon-edit') %>
        <%- end -%>
      </td>
      <td style="text-align: center;">
        <%- if User.current.allowed_to?(:manage_milestones, @project) -%>
          <%= delete_link(milestone_path(milestone)) %>
        <%- end -%>
      </td>
    </tr>
  <% end; reset_cycle %>
  </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<p><%= link_to l(:label_milestone_new, :milestone_label => label_milestone),
               new_project_milestone_path(@project, :back_url => ''),
               :class => 'icon icon-add' if User.current.allowed_to?(:manage_milestones, @project) %></p>

<%= javascript_tag do %>
  $('a#tab-milestones').text('<%= label_milestone_plural %>');
<% end %>

<%= render :partial => 'common/advanced_roadmap_footer' %>